on:
  push:

jobs:
  get-branch-lifetime:
    runs-on: ubuntu-latest
    steps:
      - name: "PR commits + 1"
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"
      - name: "Checkout PR branch and all PR commits"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}
      - name: get first commit datetime
        run: |
          echo "$env.PR_FETCH_DEPTH"
          echo "$env.PR_FETCH_DEPTH"
          git status
          git log
