on:
  pull_request:
    types: [closed]

jobs:
  get-branch-lifetime:
    runs-on: ubuntu-latest
    steps:
      - name: "Check event name"
        run: echo "${{ github.event_name }}"
      # - name: "Check json includes event"
      #   run: |
      #     echo "${{ toJson(github.event.pull_request) }}"
      #     echo "${{ toJson(github.event.pull_request.commits) }}"
      - name: "PR commits"
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} ))" >> "${GITHUB_ENV}"
      - name: "Checkout PR branch and all PR commits"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}
      - name: get lifetime of this branch
        run: |
          git log --format="%h %cI %s"
          oldest_timestamp=$(git log --format=%cI --reverse | head -1)
          now_timestamp=$(date -d now --iso-8601="seconds")
          now_sec=$(date -d now +%s)
          oldest_sec=$(date -d "$oldest_timestamp" +%s)
          lifetime=$(((now_sec - oldest_sec) / 60 / 60 ))
          echo "now:      $now_timestamp"
          echo "branched: $oldest_timestamp"
          echo "$lifetime hours"
          echo "LIFETIME=$lifetime" >> "${GITHUB_ENV}"
      - name: Post comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment "${URL}" --body "The branch for this PR has lived ${{ env.LIFETIME }} hours."
