on:
  pull_request:
    types: [opened, synchronize, edited, closed, reopened, assigned, unassigned]

jobs:
  get-branch-lifetime:
    runs-on: ubuntu-latest
    steps:
      - name: "Check event name"
        run: echo "${{ github.event_name }}"
      - name: "Check json includes event"
        run: |
          echo "${{ toJson(github.event) }}"
      - name: "PR commits + 1"
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"
      - name: "Checkout PR branch and all PR commits"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}
      - name: get first commit datetime
        run: |
          echo "FIRST_COMMIT_DATETIME=$(git log --pretty=format:"%cI" --reverse | head -1)" >> $GITHUB_ENV
      - name: get lifetime from first commit to now
        run: |
          echo ${{ env.FIRST_COMMIT_DATETIME }}
          d1=$(date -d now +%s)
          d2=$(date -d "${{ env.FIRST_COMMIT_DATETIME }}" +%s)
          lifetime=$(((d1 - d2) / 60 / 60 ))
          echo "$lifetime hours"
