on:
  pull_request:
    types: [opened, synchronize, edited, closed, reopened, assigned, unassigned]

jobs:
  get-branch-lifetime:
    runs-on: ubuntu-latest
    steps:
      - name: "Check event name"
        run: echo "${{ github.event_name }}"
      - name: "Check json includes event"
        run: |
          echo "${{ toJson(github.event) }}"
      - name: "PR commits + 1"
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"
      - name: "Checkout PR branch and all PR commits"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}
      - name: get lifetime of this branch
        run: |
          git fetch --prune --progress --no-recurse-submodules origin ${{ github.event.pull_request.base.ref }}
          git log --format=oneline
          oldest_timestamp=$(git log origin/${{ github.event.pull_request.base.ref }}..HEAD --format=%cI --reverse | head -1)
          now_timestamp=$(date -d now)
          now_sec=$(date -d now +%s)
          oldest_sec=$(date -d "$oldest_timestamp" +%s)
          lifetime=$(((now_sec - oldest_sec) / 60 / 60 ))
          echo "now:      $now_timestamp"
          echo "branched: $oldest_timestamp"
          echo "$lifetime hours"
