on:
  push:

jobs:
  get-branch-lifetime:
    runs-on: ubuntu-latest
    steps:
      - name: "Check event name"
        run: echo "${{ github.event_name }}"
      - name: "Check commits includes event"
        run: echo "${{ github.event.push.commits }}"
      - name: "PR commits + 1"
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"
      - name: "Checkout PR branch and all PR commits"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}
      - name: get first commit datetime
        run: |
          echo "commits=${{ github.event.pull_request.commits }}"
          echo "PR_FETCH_DEPTH=${{ env.PR_FETCH_DEPTH }}"
          git status
          git log
